config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post '/programmes/:id'    => 'registrations#register'
  delete '/programmes/:id'  => 'registrations#delete'

  resources :programmes do
    resources :sponsors
  end

  root 'programmes#home'

  get '/result' => 'programmes#result'
  get '/about' => 'programmes#about'
  get '/profile' => 'profile#show'
  get '/credit' => 'programmes#credit'
  get '/schedule' => 'programmes#schedule'

  get 'api/programmes/events' => 'programmes#api_events'
  get 'api/programmes/category/:category' => 'programmes#api_category'
  get 'api/programmes/sponsors' => 'programmes#api_sponsors'
  get 'api/programmes/:id' => 'programmes#api_id'
  get 'push/android' => 'android#create'
  get 'api/push/add' => 'android#new'
  get 'info' => 'sessions#info'
  get 'auth/:provider/callback', to: 'sessions#create'
  post "users/create", to: 'sessions#add_user'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/programme.rb
class Programme < ActiveRecord::Base
	has_many :sponsors
	has_many :registrations
  has_many :registered_users, through: :registrations, source: :user
end

app/controllers/programmes_controller.rb
class ProgrammesController < ApplicationController
  before_action :set_programme, only: [:show, :edit, :update, :destroy]
  require 'json'
  # GET /programmes
  # GET /programmes.json
  def home
    @color = "blue darken-3"
    @color1 = "blue darken-4"
  end

  def result
    @color = "blue darken-2"
    @color1 = "blue darken-3"

  end
  def schedule
    @color = "cyan darken-2"
    @color1 = "cyan darken-3"

  end
  def about
    @color = "red darken-3"
    @color1 = "red darken-4"

  end
  def index
    @color = "blue-grey darken-3"
    @color1 = "blue-grey darken-4"

    @programmes = Programme.all
  end
  def credit
    render :layout => "creditlayout"


  end
  # GET /programmes/1
  # GET /programmes/1.json
  def show
    @color = "green"
    @color1 = "green darken-1"
    @event_register=Programme.find(params[:id])
    if current_user!=nil
      @register=@event_register.registrations.find_by(user_id:current_user.id)
    end

  end

  # GET /programmes/new
  def new
    @color = "deep-purple darken-4"
    @programme = Programme.new
  end

  # GET /programmes/1/edit
  def edit
  end

  # POST /programmes
  # POST /programmes.json
  def create
    @color = "deep-purple darken-4"
    @programme = Programme.new(programme_params)

    respond_to do |format|
      if @programme.save
        format.html { redirect_to @programme, notice: 'Programme was successfully created.' }
        format.json { render :show, status: :created, location: @programme }
      else
        format.html { render :new }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /programmes/1
  # PATCH/PUT /programmes/1.json
  def update
    respond_to do |format|
      if @programme.update(programme_params)
        format.html { redirect_to @programme, notice: 'Programme was successfully updated.' }
        format.json { render :show, status: :ok, location: @programme }
      else
        format.html { render :edit }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
      end
    end
  end

  def api_events
    @programmes = Programme.all.as_json
    @programmes.each do |programme|
       programme = programme.map{|k,v| programme[k.to_s] = v.to_s}
    end
    @programmes = @programmes.to_json
    respond_to do |format|
       format.json {render :text => @programmes}
    end
  end

  def api_category
    @programme = Programme.where(category: params[:category]).as_json
    @programme.map{|k,v| @programme[k.to_s] = v.to_s}
    @programme = @programme.to_json

    respond_to do |format|
      format.json {render :text => @programme}
    end
  end

  def api_id
    # @programme = Programme.where(name: params[:name])
    # programme_id = @programme.pluck(:id)
    programme_id = params[:id]

      # if params[:id]
      #  @programme_sponsors_joined = Programme.includes(:sponsors).find(params[:id]).to_json(include: :sponsors)
      # end
    @programme = Programme.find(programme_id)
    @programme=@programme.as_json
    # Programme.joins(:sponsors).select("programmes.*", "sponsors.name as sponsor_name", "sponsors.about", "sponsors.link", "sponsors.amount").where(:programmes => {:id => programme_id}).to_json
    @programme.map{|k,v| @programme[k.to_s] = v.to_s}
    @programme = @programme.to_json

    respond_to do |format|
      format.json {render :text => @programme}
    end
  end

  def api_sponsors
    @sponsors = Sponsor.all.as_json
    @sponsors.each do |sponsor|
       sponsor = sponsor.map{|k,v| sponsor[k.to_s] = v.to_s}
    end
    @sponsors = @sponsors.to_json
    respond_to do |format|
       format.json {render :text => @sponsors}
    end
  end

  # DELETE /programmes/1
  # DELETE /programmes/1.json
  def destroy
    @programme.destroy
    respond_to do |format|
      format.html { redirect_to programmes_url, notice: 'Programme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programme
      @programme = Programme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programme_params
      params.require(:programme).permit(:name, :category, :branch, :start, :duration, :summary, :description, :rules, :gold_sponsor, :silver_sponsor, :bronze_sponsor,:event_image)
    end
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/views/programmes/_form.html.erb
<%= form_for(@programme) do |f| %>
  <!-- <% if @programme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programme.errors.count, "error") %> prohibited this programme from being saved:</h2>

      <ul>
      <% @programme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> -->
  <div class="col s12">
    <div class="row">

      <div class="input-field col s12">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>

   </div>
   <div class="row">
     <div class="input-field col s4">
       <%= f.label :category %><br>
       <%= f.text_field :category %>
     </div>

     <div class="input-field col s4">
       <%= f.label :branch %><br>
       <%= f.text_field :branch %>
     </div>
     <div class="input-field col s4">
       <%= f.label :duration %><br>
       <%= f.text_field :duration %>
     </div>
  </div>
  <div class="row">

  <div class="input-field col s12">
    <%= f.date_field :start, :id =>'datep', :class => 'datepicker' %>


  </div>
</div>
<div class="row">

  <div class="input-field col s12">
    <%= f.label :summary%><br>
    <%= f.text_area :summary, :class => 'materialize-textarea'%>
  </div>
</div>
<div class="row">

  <div class="input-field col s12">
    <%= f.label :description %><br>
    <%= f.text_area :description , :class => 'materialize-textarea'%>
  </div>
</div>

<div class="row">

  <div class="input-field col s12">
    <%= f.label :rules %><br>
    <%= f.text_area :rules, :class => 'materialize-textarea'%>
  </div>
</div>


<div class="row">

  <div class="input-field col s12">
    <%= f.label :Image %><br>
    <%= f.file_field :event_image, :class => 'materialize-textarea'%>
  </div>
</div>



<div class="row">

  <div class="input-field col s12">
    <%= f.label :gold_sponsor %><br>
    <%= f.text_field :gold_sponsor %>
  </div>
</div>

  <div class="row">

  <div class="input-field col s12">
    <%= f.label :silver_sponsor %><br>
    <%= f.text_field :silver_sponsor %>
  </div>
</div>

  <div class="row">

  <div class="input-field col s12">
    <%= f.label :bronze_sponsor %><br>
    <%= f.text_field :bronze_sponsor %>
  </div>
</div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn waves-effect waves-light black white-text'  %>
  </div>
</div>


<% end %>

app/views/programmes/about.html.erb
<div class="parallax-container">
     <div class="parallax">
       <%= image_tag "bg.jpg" %>
    </div>
</div>
​
<div class="section">
  <div class="abt_info">
    <div class="container">
      <div class="row">
      <div class="col s12 m5 l12">
        <div class="card-panel white">
          <span class="black-text">
            <h3>About</h3>
            <hr>
            <p> What makes FISAT the success that it is?
            Is it our tireless efforts to focus on excellence and doing our best to achieve it? Or our ability in producing students that excel in academics, extra curricular and co-curricular activites?Or our success in producing not only successful engineers, but also respectable members of society? Or having a staff that's dedicated itself to pushing itself to the limit, so that there's a better, more educated future? Or our scenic location, that inspires the students to learn, as well enjoy their college lives? Or is our ability to bring out the best in our students, and provide most of them with jobs by the time they're done with their 4 years? The answer, is all of the above. And THAT is, what makes FISAT the success that we all see today.</p>
​
            <p>There's a new level of awesomeness right at the horizon. And on the 8th and 9th of April in FISAT, is where it's all going to go down. Right at NAUTILUS 2K16! As a brainchild of the smart, hardworking and fun loving students of FISAT, it would be silly to expect anything less than what people have come to expect from us. Nautilus 2k16 is one of the most prestigious techno arts fest around the corner. Coming from the same place which has given birth to talent in arts, music and science, from one of the most rated self-financing college , Nautilus 2k16 is one of the finest events in the state. Yes, welcome to the two day cultural and techno extravaganza.
            </p>
            <h3>Why Sponsor?</h3>
            <hr>
            <p>FISAT is the most rated and sought after private self-financing college in the state. With a majority of students coming from Ernakulam, FISAT's Nautilus is the best event to sponsor. Nautilus 2k13 saw Google Developer Group hosting workshops on Android, Auto Expo nad many other events. With a participation of over 4000 students coming from all across the state, Nautilus 2k13 was rated as one of the finest tech fests of the year. And this year with the theme being 'Make in India', Nautilus 2k16 is coming back to ignite young minds once again.
            </p>
​
​
          </span>
        </div>
      </div>
    </div>
​
  </div>
  </div>
</div>
​
<div class="section">
  <div class="parallax-container">
       <div class="parallax">
         <%= image_tag "bg2.jpg" %>
       </div>
  </div>
​
</div>
​
​
<div class="section">
  <div class="abt_info">
    <div class="container">
      <div class="row">
      <div class="col l4 s12">
        <div class="card-panel white abtcards">
          <span class="black-text">
            <div class="center-align">
              <br>
            <i class="fa fa-calendar fa-5x align-centre"></i>
            <h3>2 DAYS</h3>
​
            </div>
​
            <p>So what's happening this year on 8th and 9th of April? Technical conferences, Talks, Workshops, Competitions, Fun, Expos, Cultural events - the list is endless. So drop out all your plans and get ready to spent two days at the most happening place.<p/>
​
          </span>
        </div>
      </div>
      <div class="col l4 s12">
        <div class="card-panel white abtcards">
          <span class="black-text">
            <div class="center-align">
              <br>
            <i class="fa fa-cogs fa-5x align-centre"></i>
            <h3>30+ Events</h3>
​
            </div>
​
            <p>This tech fest, is brimming with events for the learner, for the gamer, for the competitor, and also for the ones who just want to watch. There's something here for everyone. Dont' miss out because we will be expecting you!<p/>
​
          </span>
          </span>
        </div>
      </div>
      <div class="col l4 s12">
        <div class="card-panel white abtcards">
          <span class="black-text">
            <div class="center-align">
              <br>
            <i class="fa fa-group fa-5x align-centre"></i>
            <h3>4L Worth Prizes</h3>
            </div><br>
​
            <p>Bring out the champ in you and claim the glory. As this year, Nautilus brings you many events to participate and many prizes to be won. Start sharpening your skills and building up your strengths because it's going to be tight.<p/>
​
          </span>
          </span>
        </div>
      </div>
    </div>
​
  </div>
  </div>
</div>

app/views/programmes/api_events.html.erb
<%= @programme %>

app/views/programmes/api_id.html.erb
<%= @programme_sponsors_joined %>

app/views/programmes/api_sponsors.html.erb
<%= @sponsors %>

app/views/programmes/credit.html.erb
<div class="container" style="margin-top:70px">
  <div class="circlebg z-depth-2">
    <a href="/">
      <i class="fa fa-chevron-left"></i>
    </a>
  </div>
</div>
<div class="container" style="margin-top:105px">
  <div class="row">
    <div class="col s12 l2 creditauth center-align">
      <%= image_tag "credits/users-15.svg" %>

      <h5 >John Thachil</h5>
      <p >( UI/UX Developer )</p>
      <div class="cols s1"><a class="linkicon" style="font-size: 20px;" href="https://www.linkedin.com/in/johnthachil" target="_blank"><i class="fa fa-linkedin"></i></a></div>

    </div>
    <div class="col s12 l2 creditauth center-align">
      <%= image_tag "credits/users-6.svg" %>

      <h5 >Akshay S</h5>
      <p >( Rails Dev )</p>
      <div class="cols s1"><a class="linkicon" style="font-size: 20px;" href="https://in.linkedin.com/in/akshaysasidharan" target="_blank"><i class="fa fa-linkedin"></i></a></div>

    </div>
    <div class="col s12 l2 creditauth center-align">
      <%= image_tag "credits/users-9.svg" %>

      <h5 >Ashish A</h5>
      <p >( Rails Dev )</p>
      <div class="cols s1"><a class="linkicon" style="font-size: 20px;" href="" target="_blank"><i class="fa fa-linkedin"></i></a></div>

    </div>
    <div class="col s12 l2 creditauth center-align">
      <%= image_tag "credits/users-1.svg" %>

      <h5 >Arun P</h5>
      <p >( Architect )</p>
      <div class="cols s1"><a target="_blank" class="linkicon" style="font-size: 20px;" href="https://in.linkedin.com/in/arunpurushothaman"><i class="fa fa-linkedin" target="_blank"></i></a></div>

    </div>
    <div class="col s12 l2 creditauth center-align">
      <%= image_tag "credits/users-13.svg" %>

      <h5 >Sherfin S</h5>
      <p >( iOS )</p>
      <div class="cols s1"><a class="linkicon" style="font-size: 20px;" href="https://in.linkedin.com/in/sherfin-shamsudeen-896b41103" target="_blank"><i class="fa fa-linkedin"></i></a></div>

    </div><div class="col s12 l2 creditauth center-align">
      <%= image_tag "credits/users-10.svg" %>

      <h5 >Aravind M</h5>
      <p >( Android )</p>
      <div class="cols s1"><a class="linkicon" style="font-size: 20px;" href="https://in.linkedin.com/in/aravind-murali-a9605891" target="_blank"><i class="fa fa-linkedin"></i></a></div>

    </div>


  </div>
</div>
<br><br><br>

<section class="creditinfo">
  <div class="container">
    <h2>Credits</h2>
    <ul>
      <li>
        <div>SVG Icons made by
          <a href="http://www.freepik.com" title="Freepik">Freepik</a>
          from
          <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>
          is licensed by
          <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
        </div>
      </li>
      <li>Icons from <a href="https://fortawesome.github.io/Font-Awesome/">Font Awesome</a></li>
      <li>CSS Framework By <a href="materializecss.com">Materializecss</a></li>
      <li>Music From <a href="soundcloud.com">SoundCloud</a> by <a href="https://soundcloud.com/govind-s-kumar">Govind S Kumar</a></li>
      <li>Javascript/CSS Library
        <ul style="padding-left:20px;">
          <li> - Text Shadow <a href="http://bigspaceship.github.io/shine.js/">Shine JS</a></li>
          <li> - Animation <a href="https://daneden.github.io/animate.css/">Animate.css</a></li>

        </ul>
      </li>

    </ul>
    <p>The MIT License (MIT)</p>
    <p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
      modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    </p>
    <p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</p>
    <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
      HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</p>
  </div>

</section>

app/views/programmes/edit.html.erb
<h1>Editing Programme</h1>

<%= render 'form' %>

<%= link_to 'Show', @programme %> |
<%= link_to 'Back', programmes_path %>

app/views/programmes/home.html.erb
<div class="blue darken-2 homebg ">
  <div class="valign-wrapper vhome">
    <%= image_tag "shell.svg",:class => "centre-align homeimg" ,:id =>"shell" %>
    <%= image_tag "homebg.png",:class => "homeimg valign" ,:id =>"stopsound" %>


    </div>

</div>
  <div class="container">

    <div id="visualizer" class="visualizer">

      <canvas id="canva" width="800" height="200"></canvas>

      <audio id="sound" autoplay></audio>

    </div>
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
      <defs>
        <filter id="filter">
          <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
          <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 40 -7" result="filter" />
        </filter>
      </defs>

    </svg>


  </div>
</div>
<section>

  <div class="homebg2 ">
    <div class="valign-wrapper vhome">
        <h5 class="collegename">Federal Institute of Science and Technology</h5>


      </div>
  </div>
</section>


<div id="modal2" class="modal ">
  <div class="modal-content">
    <div class="row">
        <div class="col s4">
          <img style="max-width:100%" src="http://orig11.deviantart.net/407f/f/2015/103/2/3/chrome_by_dtafalonso-d67pbhl.png" alt="">
        </div>
        <div class="col s8">
  <h4 style="padding-top:16%;font-weight:100;">Use Chrome Best Experience</h4>
        </div>


    </div>
  </div>

</div>



<div class="footer valign-wrapper"  style="margin-bottom:-65px;position:absolute;">
  <div class="container valign">
    <h6 style="display:inline;">Designed and built with all the
      <i class="fa fa-heart red-text"></i>
      in the world @FISAT.</h6>
    <a href="https://www.facebook.com/nautilus2k16/" target="_blank"><i style="float:right;" class="fa fa-facebook-official fa-2x"></i></a>
    <a href="https://www.instagram.com/nautilus2k16/" target="_blank"><i style="float:right;" class="fa fa-instagram fa-2x"></i></a>

    <h6 style="display:inline;float:right;padding-right:7px;">      <a href="./credit">Credits |</a>
Follow us
    </h6>

  </div>
</div>

app/views/programmes/new.html.erb
<div class="landing1 box animate slideInDown">
    <div class="ripple"></div>

    <div class="elements">
      <br>
      <br>
      <br>
      <div class="container">
        <h3  style="font-weight:100"class="white-text">ADD EVENT</h3>
      </div>
    </div>
  </div>
  <br>
  <div class="events1">
    <div class="container">
      <div class="row">
        <div class="col s12 ">
          <div class="card-panel white animate fadeIn">
            <div class="row">
              <%= render 'form' %>

            </div>

          </div>
        </div>
      </div>
    </div>

  </div>
  

<!-- <%= link_to 'Back', programmes_path %> -->

app/views/programmes/result.html.erb
<div class="landing box animate fadeIn resultbg">
  <div class="ripple"></div>
  <div class="elements">

    <br>
    <br>
    <br>
    <div class="container">
      <div class="row">
        <div class="col s12 m6 l3"><%= inline_svg("user.svg", class: 'result_user' ) %></div>
        <div class="col s12 m6 l3 result_header"><h1>1245</h1> <p>PARTICIPANTS</p></div>

      </div>
    </div>
</div>
<div class="resultinfo">
  <div class="container">
    <div class="result_table z-depth-1 white">
      <table class="bordered highlight ">
             <thead>
               <tr>
                   <th data-field="id">NAME</th>
                   <th data-field="name">ITEM NAME</th>
                   <th data-field="price">ITEM PRICE</th>
               </tr>
             </thead>

             <tbody>
               <tr>
                 <td>Alvin</td>
                 <td>Eclair</td>
                 <td>$0.87</td>
               </tr>
               <tr>
                 <td>Alan</td>
                 <td>Jellybean</td>
                 <td>$3.76</td>
               </tr>
               <tr>
                 <td>Alan</td>
                 <td>Jellybean</td>
                 <td>$3.76</td>
               </tr>
               <tr>
                 <td>Alan</td>
                 <td>Jellybean</td>
                 <td>$3.76</td>
               </tr>
               <tr>
                 <td>Alan</td>
                 <td>Jellybean</td>
                 <td>$3.76</td>
               </tr>
               <tr>
                 <td>Jonathan</td>
                 <td>Lollipop</td>
                 <td>$7.00</td>
               </tr>
             </tbody>
           </table>
    </div>
  </div>
</div>

    <section>
      <div class="footer valign-wrapper">
        <div class="container valign">
          <h6 style="display:inline;">Designed and built with all the <i class="fa fa-heart red-text"></i> in the world by @FISAT.</h6>
             <i style="float:right;" class="fa fa-facebook-official fa-2x"></i><h6 style="display:inline;float:right;">Follow us  </h6>


        </div>
      </div>
    </section>

app/views/programmes/show.html.erb
<div class="landing2 box animate fadeIn"> 
  <div class="pattern">
    <div class="ripple"></div>

    <div class="elements">
      <br>
      <br>
      <br>
      <div class="container">
        <h3 class="black-text" style="font-weight:500;"><%= @programme.name %></h3>
      </div>
    </div>
  </div>
</div>
<br>
<div class="events1">
  <div class="container">
    <div class="row">
      <div class="col s12 ">
        <div class="rectangleshow animate fadeIn valign-wrapper">
          <a href="<%=programmes_path %>" style="color:white;">
            <i class="fa fa-angle-double-left fa-2x"></i>
          </a>
          <p style="margin-left:10px">
            Go back</p>
        </div>

        <div class="card-panel white animate fadeIn">
          <div class="container" id="cont">
            <div class="eventinfo">
              <div class="row">
                <h5 class="eventhead z-depth-1">
                  <i class="fa fa-sticky-note"></i>
                  Description</h5>
                <p style="padding-left:2%;"><%= @programme.description.html_safe %></p>

                <div class="row">
                <% if @programme.head1 != "" %>
                  <h5 class=" " style="padding-left:4%;">
                    CONTACT</h5>

                  <div class="col l7 s12 head1 push-l1 push-s1">
                      <h4> <%= @programme.head1 %></h4>
                      <h5 style="font-weight:100;line-height:2px;"><%= @programme.number1 %></h5>
                      <br>
                  </div>
                  <% if @programme.head2 != "" %>
                  <div class="col l5 s12 head2  push-s1" >
                    <h4>  <%=@programme.head2%></h4>
                    <h5 style="font-weight:100;line-height:2px;"><%=@programme.number2%></h5>
                <br>
                  <% end %>
                <% end %>


                  </div>
                </div>
                <h5 class="eventhead z-depth-1">
                  <i class="fa fa-check"></i>
                  Rules</h5>

                <p><%= @programme.rules.html_safe %></p>

                <h5 class="eventhead z-depth-1">
                  <!-- <i class="fa fa-clock-o"></i> -->
                  <!-- DURATION: <%= @programme.duration %> -->
                  <!-- <hr> -->
                  <i class="fa fa-clock-o"></i> Starts on: <%= @programme.start.strftime("%dth %b %Y (%A) ") %>
                </h5>

              </div>
              <% if @programme.prize %>
              <div class="row">            
                <div class="row awardsdiv">
                  <div class="col s12 l4">
                    <%= inline_svg("class-reward.svg", class: 'awards center-align' ) %>
                      <h5 class="center-align">1st Prize <br>
                      <% if @programme.first_prize != "" %>
                        <%= @programme.first_prize %>
                      <% else %>
                        Yay, first!
                      <% end %>
                      </h5>
                  </div>
                  <div class="col s12 l4">
                    <%= inline_svg("round-medal.svg", class: 'awards center-align' ) %>
                      <h5 class="center-align">2nd Prize <br>                      
                      <% if @programme.second_prize != "" %>
                        <%= @programme.second_prize %>
                      <% else %>
                        Yay, second!
                      <% end %></h5>

                  </div>
                  <div class="col s12 l4">
                    <%= inline_svg("militaty-medal.svg", class: 'awards center-align' ) %>
                      <h5 class="center-align">3rd Prize <br>
                      <% if @programme.third_prize != "" %>
                        <%= @programme.third_prize %>
                      <% else %>
                        Yay, third!
                      <% end %>
                      </h5>

                  </div>
                </div>
              </div>
              <% end %>
         
              <div class="row">
                <h5 class="eventhead z-depth-1">
                  <i class="fa fa-sticky-note"></i>
                  SPONSERS</h5>
                <br>
                <div class="sponbg">

                </div>
              </div>
              <% if @programme.registerable %>

              <div class="row">
                <% if user_signed_in? and @programme.team %>

                <% end  %>           
                <div id="register_ajax">
                  <% if @register%>
                      <a class="waves-effect waves-light btn registerbtn red darken-1 white-text disabled">REGISTERED</a>
                  <%end%>
                  <% if user_signed_in? and not @register%>
                    <%= link_to "REGISTER",programme_path(@event_register),remote: true ,method: :post,class:"waves-effect waves-light btn registerbtn red darken-1 white-text"%>
                  <%end%>
                </div>

              <% if not user_signed_in? %>
              <a class="waves-effect waves-light btn registerbtn red darken-1 white-text disabled">SIGN IN TO REGISTER</a>

              </li>
              <% end %>
              </div>
              <% end %>

            </div>

          </div>
        </div>
      </div>

    </div>

  </div>

</div>
<br>

<section>
  <div class="footer valign-wrapper">
    <div class="container valign">
      <h6 style="display:inline;">Designed and built with all the <i class="fa fa-heart red-text"></i> in the world by @FISAT.</h6>
      <i style="float:right;" class="fa fa-facebook-official fa-2x"></i>
      <h6 style="display:inline;float:right;">Follow us  </h6>


    </div>
  </div>
</section>